/**
 * This class is generated by jOOQ
 */
package edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> CONSTRAINT_1 = createUniqueKey(edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS, edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.PROBESET_ID);
	}
}
