/**
 * This class is generated by jOOQ
 */
package edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.MEV_PROBE_ANNOTATIONS
	 */
	public static final edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations MEV_PROBE_ANNOTATIONS = edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS;
}
