/**
 * This class is generated by jOOQ
 */
package edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MevProbeAnnotationsRecord extends org.jooq.impl.UpdatableRecordImpl<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> implements org.jooq.Record12<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1505516739;

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_VENDOR</code>.
	 */
	public void setChipVendor(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_VENDOR</code>.
	 */
	public java.lang.String getChipVendor() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_TYPE</code>.
	 */
	public void setChipType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_TYPE</code>.
	 */
	public java.lang.String getChipType() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CREATE_DATE</code>.
	 */
	public void setCreateDate(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CREATE_DATE</code>.
	 */
	public java.lang.String getCreateDate() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_SPECIES</code>.
	 */
	public void setGenomeSpecies(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_SPECIES</code>.
	 */
	public java.lang.String getGenomeSpecies() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_VERSION</code>.
	 */
	public void setGenomeVersion(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_VERSION</code>.
	 */
	public java.lang.String getGenomeVersion() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.NETAFFX_ANNOTATION_NETAFFX_BUILD</code>.
	 */
	public void setNetaffxAnnotationNetaffxBuild(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.NETAFFX_ANNOTATION_NETAFFX_BUILD</code>.
	 */
	public java.lang.String getNetaffxAnnotationNetaffxBuild() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.PROBESET_ID</code>.
	 */
	public void setProbesetId(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.PROBESET_ID</code>.
	 */
	public java.lang.String getProbesetId() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_SYMBOL</code>.
	 */
	public void setGeneSymbol(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_SYMBOL</code>.
	 */
	public java.lang.String getGeneSymbol() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_DESC</code>.
	 */
	public void setGeneDesc(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_DESC</code>.
	 */
	public java.lang.String getGeneDesc() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHR_LOCATION</code>.
	 */
	public void setChrLocation(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHR_LOCATION</code>.
	 */
	public java.lang.String getChrLocation() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.STRAND</code>.
	 */
	public void setStrand(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.STRAND</code>.
	 */
	public java.lang.String getStrand() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.REFSEQ_ACCN</code>.
	 */
	public void setRefseqAccn(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.MEV_PROBE_ANNOTATIONS.REFSEQ_ACCN</code>.
	 */
	public java.lang.String getRefseqAccn() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.CHIP_VENDOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.CHIP_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.GENOME_SPECIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.GENOME_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.NETAFFX_ANNOTATION_NETAFFX_BUILD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.PROBESET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.GENE_SYMBOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.GENE_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.CHR_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.STRAND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS.REFSEQ_ACCN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getChipVendor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getChipType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getGenomeSpecies();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGenomeVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getNetaffxAnnotationNetaffxBuild();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getProbesetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getGeneSymbol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getGeneDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getChrLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getStrand();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getRefseqAccn();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MevProbeAnnotationsRecord
	 */
	public MevProbeAnnotationsRecord() {
		super(edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS);
	}

	/**
	 * Create a detached, initialised MevProbeAnnotationsRecord
	 */
	public MevProbeAnnotationsRecord(java.lang.String chipVendor, java.lang.String chipType, java.lang.String createDate, java.lang.String genomeSpecies, java.lang.String genomeVersion, java.lang.String netaffxAnnotationNetaffxBuild, java.lang.String probesetId, java.lang.String geneSymbol, java.lang.String geneDesc, java.lang.String chrLocation, java.lang.String strand, java.lang.String refseqAccn) {
		super(edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS);

		setValue(0, chipVendor);
		setValue(1, chipType);
		setValue(2, createDate);
		setValue(3, genomeSpecies);
		setValue(4, genomeVersion);
		setValue(5, netaffxAnnotationNetaffxBuild);
		setValue(6, probesetId);
		setValue(7, geneSymbol);
		setValue(8, geneDesc);
		setValue(9, chrLocation);
		setValue(10, strand);
		setValue(11, refseqAccn);
	}
}
