/**
 * This class is generated by jOOQ
 */
package edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MevProbeAnnotations extends org.jooq.impl.TableImpl<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> {

	private static final long serialVersionUID = -94867754;

	/**
	 * The singleton instance of <code>PUBLIC.MEV_PROBE_ANNOTATIONS</code>
	 */
	public static final edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations MEV_PROBE_ANNOTATIONS = new edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> getRecordType() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_VENDOR</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> CHIP_VENDOR = createField("CHIP_VENDOR", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHIP_TYPE</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> CHIP_TYPE = createField("CHIP_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CREATE_DATE</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> CREATE_DATE = createField("CREATE_DATE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_SPECIES</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> GENOME_SPECIES = createField("GENOME_SPECIES", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENOME_VERSION</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> GENOME_VERSION = createField("GENOME_VERSION", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.NETAFFX_ANNOTATION_NETAFFX_BUILD</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> NETAFFX_ANNOTATION_NETAFFX_BUILD = createField("NETAFFX_ANNOTATION_NETAFFX_BUILD", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.PROBESET_ID</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> PROBESET_ID = createField("PROBESET_ID", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647).nullable(false), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_SYMBOL</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> GENE_SYMBOL = createField("GENE_SYMBOL", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.GENE_DESC</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> GENE_DESC = createField("GENE_DESC", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.CHR_LOCATION</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> CHR_LOCATION = createField("CHR_LOCATION", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.STRAND</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> STRAND = createField("STRAND", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * The column <code>PUBLIC.MEV_PROBE_ANNOTATIONS.REFSEQ_ACCN</code>.
	 */
	public final org.jooq.TableField<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord, java.lang.String> REFSEQ_ACCN = createField("REFSEQ_ACCN", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this);

	/**
	 * Create a <code>PUBLIC.MEV_PROBE_ANNOTATIONS</code> table reference
	 */
	public MevProbeAnnotations() {
		super("MEV_PROBE_ANNOTATIONS", edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.MEV_PROBE_ANNOTATIONS</code> table reference
	 */
	public MevProbeAnnotations(java.lang.String alias) {
		super(alias, edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.Public.PUBLIC, edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations.MEV_PROBE_ANNOTATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord> getPrimaryKey() {
		return edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.Keys.CONSTRAINT_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.records.MevProbeAnnotationsRecord>>asList(edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.Keys.CONSTRAINT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations as(java.lang.String alias) {
		return new edu.dfci.cccb.mev.annotation.domain.probe.dal.jooq.tables.MevProbeAnnotations(alias);
	}
}
